CREATE TABLE THREADS (
    ID NUMBER(7,0) GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 MINVALUE 0 NOT NULL,
    TITLE NVARCHAR2(30) NOT NULL UNIQUE,
    DESCRIPTION NVARCHAR2(200) NOT NULL,
    POSTS_COUNT NUMBER(10, 0) DEFAULT 0 NOT NULL,

    CONSTRAINT THREADS_ID_PK PRIMARY KEY (ID)
);


-- foreign key --
