CREATE TABLE POSTS (
    ID NUMBER(10, 0) GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 MINVALUE 0 NOT NULL,
    THREAD_ID NUMBER(7,0) NOT NULL,
    USER_ID NUMBER(10, 0) NOT NULL, 
    CONTENT NVARCHAR2(2000) NOT NULL, 
    CREATED_TIME DATE NOT NULL, 
    TO_POST_ID NUMBER(10,0),
    
    CONSTRAINT POSTS_ID_PK PRIMARY KEY (ID)
);


-- foreign keys --
ALTER TABLE POSTS
    ADD CONSTRAINT POSTS_TO_THREADS_ID_FK FOREIGN KEY (THREAD_ID)
        REFERENCES THREADS (ID)
ENABLE;

ALTER TABLE POSTS 
    ADD CONSTRAINT POSTS_TO_USERS_ID_FK FOREIGN KEY (USER_ID)
        REFERENCES USERS (ID)
ENABLE;