-- table creation --
CREATE TABLE ADMIN_RIGHTS (
    ID NUMBER(4, 0) GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 MINVALUE 0 NOT NULL,
    NAME NVARCHAR2(30) NOT NULL UNIQUE,
    
    CONSTRAINT ADMIN_RIGHTS_ID_PK PRIMARY KEY (ID)  
);