-- table creation --
CREATE TABLE FORUM_RANKS (
    ID NUMBER(4, 0) GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 MINVALUE 0 NOT NULL,
    NAME NVARCHAR2(30) UNIQUE NOT NULL, 
    
    CONSTRAINT FORUM_RANKS_ID_PK PRIMARY KEY (ID)
);

-- foreign keys --