CREATE TABLE USERS_INFO (
    ID NUMBER(10, 0) GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 MINVALUE 0 NOT NULL,
    USER_ID NUMBER(10, 0) NOT NULL UNIQUE,
    SEX NUMBER(3,0) NOT NULL,
    BIRTH_DATE DATE NOT NULL,
    LOCATION NVARCHAR2(20),
    REG_DATE DATE NOT NULL,
    MESSAGE_COUNT NUMBER(10,0) DEFAULT 0 NOT NULL,
    FORUM_RANK_ID NUMBER(4,0) DEFAULT 0 NOT NULL,
    PROFILE_PHOTO_PATH VARCHAR2(150) DEFAULT NULL,
    
    CONSTRAINT USERS_INFO_ID_PK PRIMARY KEY (ID)
);


-- foreign keys --
ALTER TABLE USERS_INFO 
    ADD CONSTRAINT TO_FORUM_RANKS_ID_FK FOREIGN KEY (FORUM_RANK_ID)
        REFERENCES FORUM_RANKS (ID)
ENABLE;

ALTER TABLE USERS_INFO 
    ADD CONSTRAINT USERS_INFO_TO_USERS_ID_FK FOREIGN KEY (USER_ID)
        REFERENCES USERS (ID)
ENABLE;

