ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

CREATE ROLE APPCLIENT_ROLE;

GRANT CREATE SESSION TO APPCLIENT_ROLE;



GRANT SELECT ON ADMIN.threads TO APPCLIENT_ROLE;
GRANT SELECT ON ADMIN.posts TO APPCLIENT_ROLE;
GRANT SELECT ON ADMIN.admin_rights TO APPCLIENT_ROLE;
GRANT SELECT ON ADMIN.administrators TO APPCLIENT_ROLE;
GRANT SELECT ON ADMIN.forum_ranks TO APPCLIENT_ROLE;
GRANT SELECT ON ADMIN.users TO APPCLIENT_ROLE;
GRANT SELECT ON ADMIN.users_info TO APPCLIENT_ROLE;

REVOKE SELECT ON ADMIN.THREADS FROM APPCLIENT_ROLE;

GRANT EXECUTE ON GETTHREADS TO APPCLIENT_ROLE;
GRANT EXECUTE ON GETPOSTS TO APPCLIENT_ROLE;
GRANT EXECUTE ON GETUSERINFO TO APPCLIENT_ROLE;
GRANT EXECUTE ON AUTHUSER TO APPCLIENT_ROLE;
GRANT EXECUTE ON REGISTERUSER TO APPCLIENT_ROLE;
GRANT EXECUTE ON CREATETHREAD TO APPCLIENT_ROLE;
GRANT EXECUTE ON CREATEPOST TO APPCLIENT_ROLE;

GRANT INSERT, UPDATE, DELETE ON ADMIN.THREADS TO APPCLIENT_ROLE;
GRANT INSERT, UPDATE, DELETE ON ADMIN.POSTS TO APPCLIENT_ROLE;
GRANT INSERT, UPDATE, DELETE ON ADMIN.USERS TO APPCLIENT_ROLE;
GRANT INSERT, UPDATE, DELETE ON ADMIN.users_info TO APPCLIENT_ROLE;
GRANT INSERT, UPDATE, DELETE ON ADMIN.administrators TO APPCLIENT_ROLE;




GRANT APPCLIENT_ROLE TO APPCLIENT;